id: P000688
initial_creation_type: ocr
source_metadata:
  id: bdr:W25054
  title: བོད་གངས་ཅན་གྱི་སྒྲ་རིག་པའི་མ་ལག་ཆ་ཚང་བར་བརྗོད་པའི་བསྟན་བཅོས་སྐལ་ལྡན་སྟོང་གི་འཇུག་ངོགས
  author: ''
  volumes:
    7056922a63964c748f1f20099ee545bb:
      image_group_id: I1PD352
      title: ''
      volume_number: 1
      total_pages: 138
      base_file: v001.txt
